name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Format
        run: go fmt ./...

      - name: Test
        run: go test ./...

      - name: Build
        run: go build